<a href="https://colab.research.google.com/github/jtao22/PythonAI/blob/main/ImageClassifier/imageclassifierv2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
#import 
import tensorflow as tf
from tensorflow import keras
from keras.models import Sequential as seq
from keras.layers import Dense, Flatten, Conv2D, Dropout
from keras.layers import MaxPooling2D as mp2d 
from tensorflow.keras import layers
from keras.utils import to_categorical
import numpy as np
import matplotlib.pyplot as pyplot
pyplot.style.use('fivethirtyeight')

In [15]:
#upload data
data = keras.datasets.fashion_mnist 
(trainX, trainY), (testX, testY) = data.load_data()

(60000, 28, 28)

In [13]:
#create ANN architecture
arch = keras.Sequential([
  keras.layers.Flatten(input_shape = (28,28)), #flattening images
  keras.layers.Dense(256, activation='relu'), #256 neuron layer
  keras.layers.Dense(128, activation='relu'), #128 neuron layer
  keras.layers.Dense(64, activation='relu'),  #64 neuron layer
  keras.layers.Dense(10, activation='softmax') #10 neuron output layer
])
#compile 
arch.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics = ['accuracy'])

In [16]:
#train architecture 
arch.fit(trainX, trainY, epochs=12, batch_size=64, shuffle=True)

Epoch 1/12
938/938 [==============================] - 5s 5ms/step - loss: 0.3609 - accuracy: 0.8755
Epoch 2/12
938/938 [==============================] - 5s 5ms/step - loss: 0.3498 - accuracy: 0.8785
Epoch 3/12
938/938 [==============================] - 5s 5ms/step - loss: 0.3452 - accuracy: 0.8789
Epoch 4/12
938/938 [==============================] - 5s 5ms/step - loss: 0.3431 - accuracy: 0.8801
Epoch 5/12
938/938 [==============================] - 4s 5ms/step - loss: 0.3498 - accuracy: 0.8819
Epoch 6/12
938/938 [==============================] - 5s 5ms/step - loss: 0.3278 - accuracy: 0.8839
Epoch 7/12
938/938 [==============================] - 5s 5ms/step - loss: 0.3297 - accuracy: 0.8839
Epoch 8/12
938/938 [==============================] - 5s 5ms/step - loss: 0.3201 - accuracy: 0.8863
Epoch 9/12
938/938 [==============================] - 5s 5ms/step - loss: 0.3132 - accuracy: 0.8888
Epoch 10/12
938/938 [==============================] - 5s 5ms/step - loss: 0.3125 - accuracy: 0.8878

In [17]:
#evaluate architecture
arch.evaluate(trainX, trainY)

1875/1875 [==============================] - 3s 1ms/step - loss: 0.3547 - accuracy: 0.8813


[0.3546743392944336, 0.8812833428382874]

In [20]:
#predict
predictions = arch.predict(testX[0:])
prediction = np.argmax(predictions, axis=1)
print(prediction)
print(testY)
percentage = 10000
for i in range(0,10000):
  if (testY[i] != prediction[i]):
    percentage - 1
    

print(percentage/100, "percent!")
predictions

[9 2 1 ... 8 1 5]
[9 2 1 ... 8 1 5]
100.0 percent!


array([[2.4666373e-18, 0.0000000e+00, 0.0000000e+00, ..., 1.6091535e-02,
        1.5958286e-06, 9.8186952e-01],
       [8.8976725e-05, 1.1259620e-03, 9.9299252e-01, ..., 0.0000000e+00,
        2.9383905e-04, 1.7695722e-31],
       [7.6496392e-34, 1.0000000e+00, 1.6868286e-30, ..., 0.0000000e+00,
        1.3872520e-21, 0.0000000e+00],
       ...,
       [7.3052694e-19, 5.7847260e-33, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 0.0000000e+00],
       [6.3915432e-17, 1.0000000e+00, 2.4937736e-12, ..., 0.0000000e+00,
        4.1640083e-10, 0.0000000e+00],
       [9.1893373e-05, 1.7950324e-36, 5.0453745e-14, ..., 1.5033484e-02,
        3.8554524e-03, 3.5017775e-03]], dtype=float32)