<a href="https://colab.research.google.com/github/jtao22/PythonAI/blob/main/CardiovascularDisease/cvd2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#import
import numpy as np
import pandas as pd
import matplotlib.pyplot as pyplot
import seaborn as sb
from sklearn.linear_model import LogisticRegression as lr
from sklearn.tree import DecisionTreeClassifier as dtc
from sklearn.ensemble import RandomForestClassifier as rfc
from sklearn.preprocessing import LabelEncoder as le
from sklearn.model_selection import train_test_split as tts
from sklearn.preprocessing import StandardScaler as ss
from sklearn.metrics import confusion_matrix as cm

In [ ]:
#Upload data
from google.colab import files 
files.upload()

In [13]:
#clean data
data = pd.read_csv('heartv2.csv')
data = data.dropna(axis=0)
data.head(5)

age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0   63    1   3       145   233    1  ...      0      2.3      0   0     1       1
1   37    1   2       130   250    0  ...      0      3.5      0   0     2       1
2   41    0   1       130   204    0  ...      0      1.4      2   0     2       1
3   56    1   1       120   236    0  ...      0      0.8      2   0     2       1
4   57    0   0       120   354    0  ...      1      0.6      2   0     2       1

[5 rows x 14 columns]

In [21]:
#split
trainX,testX,trainY,testY = tts(data.iloc[:,0:13].values, data.iloc[:,-1].values, test_size = 0.20, random_state = 42)


In [22]:
#create architecture 
def arch(trainX, trainY):
  #Logistic Regression
  logReg = lr(random_state = 42)
  logReg.fit(trainX, trainY)
  #Decision Tree
  DTC = dtc(criterion='entropy', random_state = 42)
  DTC.fit(trainX, trainY)
  #Random Forest Classifier
  RFC = rfc(n_estimators = 10, criterion = 'entropy', random_state = 42)
  RFC.fit(trainX, trainY)
  #print
  print('Logistic Regression Training Accuracy: ', logReg.score(trainX,trainY) * 100, '%')
  print('Decision Tree Classifier Accuracy: ', DTC.score(trainX,trainY)*100, '%')
  print('Random Forest Classifier Accuracy: ', RFC.score(trainX,trainY)*100, '%') 
  #return
  return logReg, DTC, RFC

In [23]:
#create model
models = arch(trainX, trainY)

Logistic Regression Training Accuracy:  85.53719008264463 %
Decision Tree Classifier Accuracy:  100.0 %
Random Forest Classifier Accuracy:  100.0 %


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [24]:

#test data
CM = cm(testY, models[0].predict(testX))
names = ['Logistic Regression', 'Decision Tree Classifier', 'Random Forest Classifier']
for i in range(len(models)):
  print(names[i])
  CM = cm(testY, models[i].predict(testX))
  print(CM) 
  print('Accuracy: ', (CM[0][0] + CM[1][1])/(CM[0][0] + CM[1][1] + CM[1][0] + CM[0][1]) * 100, '%')
  print()
#Diagram is:
# TP FP
# FN TN

Logistic Regression
[[25  4]
 [ 3 29]]
Accuracy:  88.52459016393442 %

Decision Tree Classifier
[[26  3]
 [ 8 24]]
Accuracy:  81.9672131147541 %

Random Forest Classifier
[[26  3]
 [ 7 25]]
Accuracy:  83.60655737704919 %

